### ISSUE TITLE
GPL-??? See count of racks scanned into Asset Audits

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/asset_audits#115]
As a user in Sample Management, I would like to see a count of how many tube racks I've scanned into Asset Audits in one go, to help avoid missing one or scanning one twice when processing large numbers.

User: Danni

**Comment by KatyTaylor** [comment]
![Screenshot 2020-03-19 at 10 11 32](https://user-images.githubusercontent.com/10407809/77056208-07006c80-69ca-11ea-94aa-e93a8dbc13a8.png)

**Comment by pjvv** [comment]
Closed since added to GPL354

![Screenshot 2020-03-23 at 10 56 54](https://user-images.githubusercontent.com/31003728/77309794-31696700-6cf5-11ea-9074-10b849a40d8d.png)
