### ISSUE TITLE
GPL-394 NX Bed Verification For Heron Stamp

### ISSUE THREAD

**Issue by rl15** [sanger/asset_audits#129]
**User story**
GPL-394 As Product leads for Sample management  (Danni & Adam) we would like in Asset Audits,  Bed verification on the NX to stamp from fluidx racks, kingfisher or eppendorf plates to Eppendorf twintec plates to verify upto 4 source and 4 destination are correctly paired to prevent sample switches

**Who the primary contacts are for this story**
Danni, Adam F

**Acceptance criteria**
To be considered successful the solution must allow:

i. Inputs
 
1.	Asset audit to accept 1-4 source plates with barcodes 
a.	SA barcoded 96 tube fluid-x rack (Example: SA00914070) or 
b.	kingfisher barcoded plate (Example: TBD) or
c.	DN barcoded Eppendorf
 
2.	1-4 destination Eppendorf twintec plates with DN barcode (Example: DN624334R)
 
3.	Sample Management Beckman NX, with barcode 009851
 
ii. Bed verify mapping

Source Bed Number |  Destination Bed Number
2 |  3
5 |  6
8 |  9
11 | 12

iii) Outputs

None

**Additional context**

Email chain on 14th April, Danni, Adam, Neil, Andrew, James M

**Comment by KatyTaylor** [comment]
`instrument = Instrument.find_by(name: 'Beckman NX')`
`process = InstrumentProcess.create!(name: 'COVID stamp', key: 'covid_stamp')`
`InstrumentProcessesInstrument.create!(instrument_id: instrument.id, instrument_process_id: process.id, bed_verification_type: 'Verification::DilutionPlate::Nx')
`

**Comment by KatyTaylor** [comment]
Test steps:

Setup:
- Checkout Sequencescape this branch https://github.com/KatyTaylor/sequencescape/tree/GPL-394-asset-audits-bed-verification-heron and start the server
- Checkout Asset Audits this branch https://github.com/sanger/asset_audits/tree/GPL-394-bed-verification-heron-lite and start the server
- Go to /admin/instruments
- If an instrument called 'Beckman NX' is **not** there, make one using 'New instrument' link:
    - Name: Beckman NX
    - Barcode: 1
- Click 'Manage Beckman NX'
- Fill out 'Add bed to instrument' form with the following:
    - Bed name: p2
    - Barcode: 2
    - Bed Number: 2
- Repeat for beds p3, p5, p6, p8, p9, p11 & p12
- Run script from comment above to insert 'process'
- In Sequencescape, use 'Generate Tube Racks' UAT action to generate 4 tube racks
- In Sequencescape, use plates/new page to stamp those 4 tube racks to plates (LHR RT type, but shouldn't matter)

Test:
- Go to /process_plates/new
- User barcode = your swipecard in SS
- Instrument barcode = 1
- Instrument process = COVID stamp
- Fill out the beds with the barcodes you created above (2, 3, 5, 6, 8, 9, 11, 12)
- Fill out the plates with the barcodes from the plates/new output in Sequencescape
    - top row of plates is the tube rack barcodes
    - bottom row of plates is the resulting plates barcodes
- Click Submit
- Verify there are no errors

**Comment by KatyTaylor** [comment]
Deployment:
* Sequencescape
* Asset Audits
    * Run rake tast `covid_stamp:add`

**Comment by andrewsparkes** [comment]
Users happy with UAT.
Requested minor name change to instrument process, from 'COVID Stamp' to 'COVID 96 Well STAMP'.
Change made in code and new pull request made.
