### ISSUE TITLE
GPL-409 Create plate in SS programatically by calling the lighthouse service

### ISSUE THREAD

**Issue by pjvv** [sanger/asset_audits#130]
**User story**
As a dev team we would like AA to call the lighthouse service when the 'receive_plate' process occurs (similar to tube racks) so that the lighthouse service can find the sample data and create a plate in SS with that data.

**Who the primary contacts are for this story**
Philip

**Acceptance criteria**
To be considered successful the solution must allow:
1. the lighthouse service needs to be called (HTTP POST) with each barcode scanned in with the 'receive_plate' process

**Additional context**
Blocked by sanger/crawler#2

**Comment by rl15** [comment]
Possibly deprecate from stand up 29th

**Comment by pjvv** [comment]
Edited title and content, this story is still required.
