### ISSUE TITLE
GPL-424  bed verification on the Hamilton Star for 1ml lysate extraction protocol

### ISSUE THREAD

**Issue by rl15** [sanger/asset_audits#134]
**User story**
GPL-424 | As R&D (Diana R) we would like bed verification on the Hamilton Star for 1ml lysate extraction protocol currently in development [Hinxton #688840]

**Who the primary contacts are for this story**
Diana R
Scott T
Danni W

**Acceptance criteria**
To be considered successful the solution must allow:

Either 1 or 2 plates can be processed at a time.
Source = Heron Lysed Plate (2ml deep well - 96)
Destination = LHR stock (96 well PCR plate)
 
Instrument : Hamilton STAR in sample management (L3 PRE).
Source lysed plate 1, bed 4 > Destination plate LHR stock 1, bed 34
Source lysed plate 2, bed 5 > Destination plate LHR stock 2, bed 35

**Additional context**
Was https://rt.sanger.ac.uk/Ticket/Display.html?id=688840 

From Danni relating to where the bed verification will happen given the extraction is tracked in Samples Extraction "SM usually use asset audits for bed verification, but limber is also an option which the SM team are also familiar with. To keep things consistent in SM I would go for asset audits but if it’s easier for psd to set it up in Limber that’s fine too."

Post Deployment:
Run this rake task to set up the instrument process:
`bundle exec rake lysates_extraction_hamilton:add`

**Comment by rl15** [comment]
Diane R wrote Tuesday, 28 April 2020 at 13:36

Actually, based on our most recent testing we think that GPL-424 (Hamilton) is closer to being ready than GPL-422(Bravo). In light of that please could the Hamilton (This backlog item - rl15) story be prioritised over the Bravo.

**Comment by JamesGlover** [comment]
Sent query

> Hello all,
> 
> I might be mistaken, but I don't think we've currently got anything tracking that particular Hamilton.
> 
> 1) Is the robot barcode? If so, do you have the barcode as read by a scanner
> 2) Are the beds barcoded? If so, can you provide the bed barcodes as read by a scanner. (Preferably all of them, not just the ones used in this protocol)
> 
> Thank you

**Comment by andrewsparkes** [comment]
Di has reported issue with the tips lifting the tubes (see RT issue) and requested this issue be put on hold for now.

**Comment by rl15** [comment]
Scott T writes: Tuesday, 23 June 2020 at 10:25

I have just realised that we need to make an amendment to bed positions in GPL-424 due to the deck being renumbered to better fit cherry picking.
 
Plate 1 source position = Bed 4, Plate 1 destination position = Bed 34            
Plate 1 source position = Bed 5, Plate 1 destination position = Bed 35            
 
Apologies for the late change.

**Comment by andrewsparkes** [comment]
Code in PR request:
https://github.com/sanger/asset_audits/pull/189
working with one outstanding issue - columns are not highlighting as they should (i.e. source and matching destination).
This was working before update of bed names from 'Pnn' to 'SCRCnn' and 'DESTnn'.
Code for highlights is in: 
app/views/bed_layouts/_groupable_javascript.html.erb
and
app/views/bed_layouts/_shared_robot_javascript.html.erb
