### ISSUE TITLE
GPL-447 Prevent multiple presses of submit

### ISSUE THREAD

**Issue by pjvv** [sanger/asset_audits#150]
**User story**
As a dev team we would like to prevent asset audits from submitting audits multiple times. This causes multiple calls to the lighthouse/wrangler service and slows the process down.

**Who the primary contacts are for this story**
Philip

**Acceptance criteria**
To be considered successful the solution must allow:
1. prevent requests from being sent multiple times
2. let user know that a request is in progress

**Additional context**

**Comment by JamesGlover** [comment]
See the disable with property of submit buttons in rails forms: https://apidock.com/rails/v5.2.3/ActionView/Helpers/FormTagHelper/submit_tag

**Comment by pjvv** [comment]
> See the disable with property of submit buttons in rails forms: https://apidock.com/rails/v5.2.3/ActionView/Helpers/FormTagHelper/submit_tag

Thanks @JamesGlover , will give it a try.
