### ISSUE TITLE
GPL-486 update how the wrangler is called

### ISSUE THREAD

**Issue by pjvv** [sanger/asset_audits#160]
**User story**
As a dev team we need to update how the wrangler is called since it now uses a POST.

**Who the primary contacts are for this story**
Philip

**Acceptance criteria**
To be considered successful the solution must allow:
1. update the `lib/wrangler.rb` file to call the wrangler service using POST

**Additional context**

**Comment by rl15** [comment]
Can we update the documentation.
This: https://app.lucidchart.com/invitations/accept/3b985921-89f5-4bec-90ed-52b580382270 
& ? this: https://app.lucidchart.com/invitations/accept/b8490157-c261-433e-9e72-8466887ecc63
