### ISSUE TITLE
GPL-547 BUG - times out when scanning in barcodes

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/asset_audits#175]
**Describe the bug**
If many barcodes are scanned in ('receive plates' process), the browser / rails times out. It continues running in the background, but the user gets an error. We should look at one or more of:
- making the import process faster
- set a limit on number of barcodes scanned
- make the process asynchronous

**RT Ticket Number**
This came out of https://rt.sanger.ac.uk/SelfService/Display.html?id=692892
Danni scanned in 52 barcodes ('lighthouse'), and got a timeout error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page /process_plates/new
2. Enter your user barcode and the barcode for an instrument which has the 'Receive plates' process
3. Scan around 50 barcodes into the box and hit submit
4. See timeout error

**Expected behaviour**
No timeout error. Ideally user should be shown results of scanning in the barcodes. Difficulty is, if we make is asynchronous to avoid the timeout, we might sacrifice usability as will be harder to display the results.

**Comment by KatyTaylor** [comment]
Me to Danni 22/06:

> Regarding your RT ticket you put in today about Asset Audits timing out (https://rt.sanger.ac.uk/SelfService/Display.html?id=692892) –
>  
> I’ve put an issue in our backlog to deal with this (GPL-547).
> The quickest thing to do is to put in a limit of the number of barcodes scanned – I think we would set this at around 20 to prevent time outs. We can do something to make it possible to scan more at a time without hitting an error, but it would take longer. How important is it to you to be able to scan more than 20 at a time?

Response from Danni:

> A 20 limit is fine, would it be possible to have a line count or message stating 20 barcodes at once?

**Comment by KatyTaylor** [comment]
![Screenshot 2020-06-26 at 13 50 53](https://user-images.githubusercontent.com/10407809/85858772-19055e80-b7b4-11ea-8ed4-400bf0f98cf7.png)
![Screenshot 2020-06-26 at 13 50 45](https://user-images.githubusercontent.com/10407809/85858775-1a368b80-b7b4-11ea-8da5-dc410435d7fb.png)

**Comment by JamesGlover** [comment]
Closing this as it appears to be done.
