### ISSUE TITLE
DPL-310 Destruction feature to move labware to LabWhere 'destroyed' location (C=M)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/asset_audits#339]
**User story**
As a Sample Management or Heron user I would like the destruction feature of Asset Audits to move the labware to a special location in LabWhere that I use to indicate that labware are destroyed, so that I don't have to go to LabWhere separately to do this.

**Who are the primary contacts for this story**
Danni & Anna G

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Labware marked for destruction in Asset Audits should also have their locations updated in LabWhere, to a special 'destroyed' location.
- [x] There is messaging on the page to explain this is what will happen, and feedback to say whether the update in LabWhere was successful or not.

**Additional context**
Asset Audits has its own event-based way of marking a labware as destroyed. However, the Asset Audits feature is not being used, and the accepted way of marking labware as destroyed is to use these special locations in LabWhere.

**Comment by TWJW-SANGER** [comment]
There are a 6 "Destroyed" locations within labwhere (search for 'Destroyed'). We may need clarity on which one to use or allow users to choose....

**Comment by SujitDey2022** [comment]
A process improvement requirement to help reduce manual efforts when destroying multiple samples and derivatives.

**Comment by SujitDey2022** [comment]
09Jan2024 - Team Discussion

1. Which of the 6 Destroyed location is to be considered as 'Destroyed' location?
2. Do we need to identify the need for data migration from some or all locations to the new one?

**Comment by SujitDey2022** [comment]
17Jan2024 - Team Discussion

1. Create new single location to be created in 'Labwhere' with destroyed labware type.
2. Currently tableau is used to report on archived samples which may also have location information.
3. Nice to have people destroying samples using Asset Audits and only limited access for the ones who can do it in 'Labwhere'

**Comment by yoldas** [comment]
Notes:
- Destroying labware process does not require instrument barcode.
```
destroy_labware:
  name: Destroying labware
  request_instrument: false
  visual_check_required: false
```
- Asset Audits uses Sequencescape API for users, however Labwhere has its own users table.

**Comment by yoldas** [comment]
Story1: Update swipecard in SS Profile will update Labware swipecard as well.
Story2: Create an endpoint in Labwhere for sync.ing  barcode as well and provide a UI? to sync.
Task: Write down a confluence page to explain the auth and relationships of there apps.

**Comment by yoldas** [comment]
I have done some further research and written a Confluence article: 
[User authentication, swipe-cards, barcodes and relationships between apps](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/User+authentication%2C+swipe-cards%2C+barcodes+and+relationships+between+apps)

**Comment by yoldas** [comment]
I have created the following stories for synchronising the user swipe-cards and barcodes across applications:
- sanger/labwhere#784
- sanger/labwhere#785
