### ISSUE TITLE
DPL-311 Destroy whole boxes at once (C=M)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/asset_audits#340]
**User story**
As a Sample Management user I would like to be able to destroy whole boxes at once, where a box is a location in LabWhere. This will save me having to scan each labware within the box individually.

**Who are the primary contacts for this story**
Danni

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can scan a LabWhere location into the destruction feature in Asset Audits
- [ ] The number of labware within that box is displayed on the screen, so I can visually check it matches reality
- [ ] When I press go, the destruction feature works as normal for each of the labware within that box (checks if they are suitable based on lifespan, creates a destruction event for them, and updates the location in LabWhere, assuming https://github.com/sanger/asset_audits/issues/339 has been done)
- [ ] Labwhere location scanned should not contain child locations. Only allow destruction of labware within bottom-level locations.
- [ ] Scanned box if contains even a single non-expired labware, then the box should not be destroyed.

**Dependencies**
Assumes https://github.com/sanger/asset_audits/issues/339 has been done already, although they could probably also be done in the opposite order.

**Comment by SujitDey2022** [comment]
Will help improve process and reduce manual errors

**Comment by SujitDey2022** [comment]
Refinement PSD 21/11/2023:

1. Scan box into Asset Audit and will it check the lifespan of the samples in the box? 
2. Need to mark applicable samples as destroyed
3. Add validation to limit moving to destroyed location in Labwhere (Future scope)

**Comment by seenanair** [comment]
Hi @Danniw373 , I have a question on this story - 'DPL-311 - Destroy whole boxes at once'.

In the story, it mentions, "Labwhere location scanned should contain child locations." I hope this means that the destruction of labware will only be allowed in locations that have child locations within them. However, if the scanned location doesn't have any child locations and directly contains labware, shouldn't that be allowed as well?
