### ISSUE TITLE
DPL-368 Set lifespan on labware [C=S]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/asset_audits#363]
**User story**
As a sample management user, I would like the 'lifespan' to be set on various types of labware, so I can use the Asset Audits feature to assist with labware destruction.

**Who are the primary contacts for this story**
Katy, Danni

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Set 'lifespan' field on 'purpose' records as recorded in the attached spreadsheet 

[Labware purpose list.xlsx](https://github.com/sanger/asset_audits/files/8660315/Labware.purpose.list.xlsx)

**Additional context**
This is a data change only, no code. This is in the Sequencescape database, although the relevant feature is in the Asset Audits app.

From Danni about list:
> This list covers all short read sequencing pipelines, bespoke and long lead excluding TOL. I have also not included stock plate this should stay as do not destroy.

**Comment by SujitDey2022** [comment]
Will help improve process
